[project]
name = "tello-programs"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "djitellopy>=2.5.0",
    "keyboard>=0.13.5",
    "opencv-python>=4.12.0.88",
    "pillow>=12.0.0",
    "pygame>=2.6.1",
]
